### ISSUE TITLE
Improve icon

### ISSUE THREAD

**Issue by SebastianZ** [firebug/fireangular#1]
The Firebug symbol used within the extension icon is outdated and should not be used anymore. You can get the new icon from the [Firebug artwork repo](https://github.com/firebug/artwork/tree/master/2010).

Though as FireAngular also works without Firebug, the Firebug icon is actually not needed at all and could just be removed.

Sebastian

**Comment by rpl** [comment]
@SebastianZ how about the new one in 9062a4e?

**Comment by SebastianZ** [comment]
The bug is a bit big, but ok.
What's the reason you didn't remove the Firebug icon from the 32x32 and 16x16 icon?

Sebastian

**Comment by rpl** [comment]
On Thu, Apr 16, 2015 at 4:57 PM, Sebastian Zartner <notifications@github.com

> wrote:
> 
> The bug is a bit big, but ok.
> What's the reason you didn't remove the Firebug icon from the 32x32 and
> 16x16 icon?
> 
> Just to suggest to the user that the decoration is related to the
> FireAngular DOM sidebar and not to another AngularJS addon.

But I'm not very good on this kind of stuff, so if you think the bug is too
big in the 16x16 icon I will follow your suggestion ;-)

## 

Luca Greco @ Alca Società Cooperativa
http://github.com/rpl

**Comment by SebastianZ** [comment]
> > The bug is a bit big, but ok.
> > What's the reason you didn't remove the Firebug icon from the 32x32 and 16x16 icon?
> 
> Just to suggest to the user that the decoration is related to the FireAngular DOM sidebar and not to another AngularJS addon.

I guess you refer to [AngScope and ng-inspect](https://addons.mozilla.org/de/firefox/search/?q=angular&appver=any&platform=all). Seems legit, though I doubt that people will install multiple of those add-ons at once.

> But I'm not very good on this kind of stuff, so if you think the bug is too big in the 16x16 icon I will follow your suggestion ;-)

Thanks, I'm also just a programmer, not a designer (while I (re-)created all the Firebug icons as SVGs for 2.0). Anyway, my reasoning is not that strong, I just feel it's a little better without.

Sebastian

**Comment by rpl** [comment]
On Thu, Apr 16, 2015 at 5:33 PM, Sebastian Zartner <notifications@github.com

> wrote:
> 
> I guess you refer to AngScope and ng-inspect
> https://addons.mozilla.org/de/firefox/search/?q=angular&appver=any&platform=all.
> Seems legit, though I doubt that people will install multiple of those
> add-ons at once.
> 
> yep, and I agree that a "6x6 px" bug doesn't do a great job anyway, I'm
> definitely convinced, I'm going to remove the bug from the 16x16 icon ;-)
> 
>  But I'm not very good on this kind of stuff, so if you think the bug is
> too big in the 16x16 icon I will follow your suggestion ;-)
> 
> Thanks, I'm also just a programmer, not a designer (while I (re-)created
> all the Firebug icons as SVGs for 2.0). Anyway, my reasoning is not that
> strong, I just feel it's a little better without.
> 
> I mean that my graphic/designer taste and skills are definitely sub-optimal
> :-P

## 

Luca Greco @ Alca Società Cooperativa
http://github.com/rpl
